# ==========================================
# 🟢 SERVIÇO A (Validador e Proxy)
# Porta: 8080 (Onde você bate externamente)
# ==========================================
POST http://localhost:8080/weather/cep HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "cep": "03986000"
}


###

# ==========================================
# 🔵 SERVIÇO B (Orquestrador e Clima)
# Porta: 8082 (Para testes isolados do Serviço B)
# ==========================================
GET http://localhost:8082/weather?cep=29902555
Host: localhost:8080
Content-Type: application/json